name: Test creating a pull request

on:
  pull_request:
    types:
      - opened

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Print something
        run: |
          echo "something"
